import fs from 'node:fs'
import { TestsWriter } from "./modules/TestsWriter"
import TestsSpecHandler from "./modules/TestsSpecHandler"

const pathToTests = './__tests__/autoGenerated'

// generate folder to tests if not exists
fs.mkdirSync(pathToTests, { recursive: true })


// get tests specification
const testsSpecification = fs.readFileSync('./__tests__/example.json', 'utf-8')

const parsedAndValidatedTestsSpec = TestsSpecHandler.parseAndValidateFromJSON(testsSpecification)

generateTests()
deleteUnlisted()

function generateTests() {
    let contentForEmptyFile = ``

    TestsWriter.checkAndCreateAllMissingFolders({
        currentDepth: 0,
        currentFolder: parsedAndValidatedTestsSpec,
        currentPath: pathToTests,
        depthLimit: 10,
    })
    
    TestsWriter.checkAndCreateMissingFilesForAllFoldersAndSubFolders({
        currentDepth: 0,
        depthLimit: 10,
        currentFolder: parsedAndValidatedTestsSpec,
        currentPath: pathToTests,
        contentForEmptyFile: contentForEmptyFile,
    })
    
    TestsWriter.enterFilesToCheckAndWriteControlledLines({
        currentDepth: 0,
        depthLimit: 10,
        currentFolder: parsedAndValidatedTestsSpec,
        currentPath: pathToTests,
        parsedTestsSpecification: parsedAndValidatedTestsSpec,
    })

}

function deleteUnlisted () {
    TestsWriter.checkAndDeleteUnlistedFilesForAllFoldersAndSubFolders({
        currentDepth: 0,
        depthLimit: 10,
        currentFolder: parsedAndValidatedTestsSpec,
        currentPath: pathToTests,
    })
}

